from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.models import Base  # Import the declarative base from models

# URL for the SQLite database
DATABASE_URL = "sqlite:///hydroscope.db"

# Create the SQLAlchemy engine
# 'echo=True' will log all SQL statements generated by SQLAlchemy (for debugging)
engine = create_engine(DATABASE_URL, echo=True)

# Create a configured "Session" class
# This sessionmaker factory will generate new Session objects when called
SessionLocal = sessionmaker(bind=engine)

# Function to initialize the database
def init_db():
    # Create all tables defined by the Base's subclasses (i.e., all models)
    # This will create tables in the database if they do not already exist
    Base.metadata.create_all(bind=engine)
