"""Initial tables

Revision ID: 1048c4c5d7d6
Revises: 
Create Date: 2025-12-04 21:52:31.775103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1048c4c5d7d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hydrologi_soil_group', sa.String(), nullable=True),
    sa.Column('default_cn', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soil_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hydrologic_soil_group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watershed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=False),
    sa.Column('land_use_id', sa.Integer(), nullable=True),
    sa.Column('soil_type_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['land_use_id'], ['land_use.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['soil_type_id'], ['soil_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rainfall_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('watershed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['watershed_id'], ['watershed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runoff_calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watershed_id', sa.Integer(), nullable=True),
    sa.Column('cn_used', sa.Integer(), nullable=True),
    sa.Column('run_off_depth_mm', sa.Float(), nullable=True),
    sa.Column('run_off_volume_m3', sa.Float(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['watershed_id'], ['watershed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runoff_calculation')
    op.drop_table('rainfall_event')
    op.drop_table('watershed')
    op.drop_table('soil_type')
    op.drop_table('region')
    op.drop_table('land_use')
    # ### end Alembic commands ###
